name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Android NDK toolchain Setup
       # You may pin to the exact commit or the version.
       # uses: ravinderjangra/android-ndk-toolchain-setup@88bfbd8e61af597832637fb9d2f81a7cc68d1331
      uses: ravinderjangra/android-ndk-toolchain-setup@0.2
       with:
        # Android API
         api: # default is 21
         # Platform arch
         arch: 
         # Path to use for NDK toolchain
         install-location: 
         # Force install toolchain
         force: false # optional, default is false
         # Add toolchain to the path
         add-to-path: true # optional, default is true

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
